apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::047923129740:user/clo835
      username: clo835admins
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::047923129740:role/eksctl-clo835-nodegroup-nodegroup-NodeInstanceRole-AYCNPMP9YE4F
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2022-07-13T14:35:47Z"
  name: aws-auth
  namespace: kube-system
  

